### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kumicoo** [Bluefissure/Inviter#11]
Idk bro it just doesnt work, doesnt invite people

**Comment by Kumicoo** [comment]
It shows 1.1.0.0

**Comment by Kumicoo** [comment]
I get "Unable to get CID"

**Comment by Bluefissure** [comment]
Are you inviting in eureka/bozja?

**Comment by Kumicoo** [comment]
Im sorry, i am apparently a smooth brain, Eureka check was on, it does work. I apologize. But i could have sworn i tried every settings. Oh well.

**Comment by Bluefissure** [comment]
Yeah the invitation in eureka/bozja instance is kinda different than the outside, which needs the eureka checkbox be checked.
It should be automatically checked once you entered such instances but you can also manually check it.
