### ISSUE TITLE
This plugin failed to load.

### ISSUE THREAD

**Issue by YukiExcalibur** [Bluefissure/Inviter#12]
![QQ截图20220911144742](https://user-images.githubusercontent.com/17423462/189515798-eb397606-2b8d-4d00-ac99-044ec95b77b0.png)
我用了XIVLauncherCN 启动器，更新了新invite就出现了这个提示，版本是1.1.0.0

**Comment by YukiExcalibur** [comment]
![QQ截图20220911145704](https://user-images.githubusercontent.com/17423462/189516048-71e53058-be33-4539-95af-76ff3afe7f79.png)

**Comment by YukiExcalibur** [comment]
![QQ截图20220911150049](https://user-images.githubusercontent.com/17423462/189516101-1471ec4a-dbbe-49df-a9c8-66ce75044f67.png)

**Comment by Bluefissure** [comment]
请使用 `https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster_api6.json`
