### ISSUE TITLE
7.0 update

### ISSUE THREAD

**Issue by Iniquity1** [Bluefissure/Inviter#16]
Were there any plans to update this to 7.0? I would like that very much. Thank you!

**Comment by Bluefissure** [comment]
I updated the sigs yesterday, but still need to update the group manager in order to be compatible with the old functionalities, probably will release a new one later today.

**Comment by Bluefissure** [comment]
should be updated

**Comment by Iniquity1** [comment]
Thanks for the speedy update! Cheers!
